import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema21748627457817 implements MigrationInterface {
    name = 'InitialSchema21748627457817'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "installment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "email" character varying NOT NULL, "reference" character varying NOT NULL, "propertyId" character varying NOT NULL, "investmentType" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "frequency" character varying NOT NULL, "status" character varying NOT NULL, "startedAt" TIMESTAMP NOT NULL, "nextPaymentDate" TIMESTAMP NOT NULL, "subscriptionCode" character varying NOT NULL, "authorizationCode" character varying NOT NULL, "customerCode" character varying NOT NULL, "paid" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c79b5b68e8b6293a0210ce7dbda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_usertype_enum" AS ENUM('landlord', 'tenant', 'mananger', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP DEFAULT now(), "updatedAt" TIMESTAMP DEFAULT now(), "deletedAt" TIMESTAMP, "email" text NOT NULL, "name" character varying, "status" text, "phoneNumber" text, "password" character varying NOT NULL, "howYouFoundUs" text, "referralCode" text, "gender" text, "streetAddress" text, "city" text, "state" text, "country" text, "idType" text, "idNumber" text, "bvn" text, "idDocument" text, "accountNumber" text, "accountName" text, "bankName" text, "profilePicture" jsonb, "isActive" boolean DEFAULT true, "userType" "public"."users_usertype_enum", "paystackAuthCode" text, "autoCharge" boolean DEFAULT false, "otp" character varying, "isOtpVerified" boolean DEFAULT false, "otpCooldownExpires" TIMESTAMP, "isEmailVerified" boolean DEFAULT false, "isAdmin" boolean NOT NULL DEFAULT false, "pendingEmail" character varying, "emailVerificationToken" character varying, "emailVerificationTokenExpires" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallet_transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid NOT NULL, "userId" character varying NOT NULL, "type" character varying NOT NULL, "amount" numeric(10,2) NOT NULL DEFAULT '0', "reference" character varying, "reason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_62a01b9c3a734b96a08c621b371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "balance" numeric(12,2) NOT NULL DEFAULT '0', "paystackCustomerCode" text, "paystackCustomerId" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "properties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "type" character varying NOT NULL, "listingType" character varying NOT NULL, "category" character varying, "address" character varying NOT NULL, "description" text NOT NULL, "imageDoc" jsonb, "bedrooms" integer, "bathrooms" integer, "toilets" integer, "propertySize" character varying, "floorLevels" integer, "parkingAvailable" boolean NOT NULL DEFAULT false, "amenities" text, "rentalPrice" numeric(12,2), "rented" boolean NOT NULL DEFAULT false, "serviceCharge" numeric(12,2), "securityDepositRequired" boolean DEFAULT false, "advanceRentPayment" numeric(12,2), "numberOfMonths" integer, "rentalAgreementDoc" jsonb, "latePaymentPolicy" text, "agreeToTerms" boolean NOT NULL DEFAULT false, "returnDuration" text, "percentageReturns" text, "images" jsonb NOT NULL DEFAULT '[]', "interestRate" numeric, "owner" text, "numberOfUnit" integer, "pricePerUnit" numeric(12,2), "pricePerShare" numeric(12,2), "price" numeric(12,2), "status" text, "resaleValue" integer, "potentialRoi" numeric, "renovationDetails" text, "constructionStatus" text, "estimatedCompletion" text, "minimumInvestment" numeric(12,2), "fullInvestmentPrice" numeric(12,2), "investmentDuration" numeric, "investmentGoal" numeric(12,2), "amountRaised" numeric(12,2), "estimatedRentalIncomePerMonth" numeric(12,2), "projectedProfitShareIfSold" text, "renovationType" text, "paymentPlan" text, "estimatedTimeline" text, "reasonForDecline" text, "renovationCost" numeric(12,2), "approved" boolean NOT NULL DEFAULT false, "listedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2d83bfa0b9fcd45dee1785af44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plan" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "amount" integer NOT NULL, "interval" character varying NOT NULL, "plan_code" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "propertyId" character varying NOT NULL, "investmentType" character varying NOT NULL, "shares" integer NOT NULL, "paidAt" date, "reference" character varying NOT NULL, "email" character varying NOT NULL, "customerCode" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "legals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "propertyId" character varying NOT NULL, "supportingDocument" jsonb, "preferredLegalAction" character varying NOT NULL, "legalIssue" character varying NOT NULL, "caseStatus" character varying NOT NULL, "legalPackageType" character varying NOT NULL, "approved" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7261df6ad1f2b8abdb02973f34f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "installment" ADD CONSTRAINT "FK_a93dcc84156c13b3883a87c1b9a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transaction" ADD CONSTRAINT "FK_07de5136ba8e92bb97d45b9a7af" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "wallet_transaction" DROP CONSTRAINT "FK_07de5136ba8e92bb97d45b9a7af"`);
        await queryRunner.query(`ALTER TABLE "installment" DROP CONSTRAINT "FK_a93dcc84156c13b3883a87c1b9a"`);
        await queryRunner.query(`DROP TABLE "legals"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "plan"`);
        await queryRunner.query(`DROP TABLE "properties"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TABLE "wallet_transaction"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_usertype_enum"`);
        await queryRunner.query(`DROP TABLE "installment"`);
    }

}
